apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-fitness-blue
  namespace: aceest-fitness
  labels:
    app: aceest-fitness
    version: blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aceest-fitness
      version: blue
  template:
    metadata:
      labels:
        app: aceest-fitness
        version: blue
    spec:
      containers:
      - name: aceest
        image: himanshug619/aceest-fitness:v1.4
        ports:
        - containerPort: 5000
