apiVersion: apps/v1
kind: Deployment
metadata:
name: aceest-v1
labels:
app: aceest
version: v1
spec:
replicas: 2
selector:
matchLabels:
app: aceest
version: v1
template:
metadata:
labels:
app: aceest
version: v1
spec:
containers:
- name: aceest
image: yourdockerid/aceest:v1
ports:
- containerPort: 5000